

services:
  backend:
    build: .
    container_name: app_sendmail
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - TZ=Asia/Tokyo
    networks:
      - sendmail

  frontend:
    image: nginx:stable
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - sendmail
networks:
  sendmail: