services:
  app:
    build: .
    container_name: fastapi_app
    volumes:
      - ./app:/app
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/html:/usr/share/nginx/html
      - ./logs:/var/log/nginx
    depends_on:
      - app
