/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BottomNavigation: typeof import('./components/BottomNavigation.vue')['default']
    DrinkMenusList: typeof import('./components/DrinkMenusList.vue')['default']
    FoodMenusList: typeof import('./components/FoodMenusList.vue')['default']
    ImportCSVBtn: typeof import('./components/ImportCSVBtn.vue')['default']
    MenuCategory: typeof import('./components/MenuCategory.vue')['default']
    NavigationOrder: typeof import('./components/NavigationOrder.vue')['default']
    OrderConfirm: typeof import('./components/OrderConfirm.vue')['default']
    OrderHistory: typeof import('./components/OrderHistory.vue')['default']
    PlaybackAudio: typeof import('./components/PlaybackAudio.vue')['default']
    RecordingButton: typeof import('./components/RecordingButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Window: typeof import('./components/Window.vue')['default']
  }
}
