/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBottomNavigation: typeof import('./components/layout/AppBottomNavigation.vue')['default']
    AppNavigation: typeof import('./components/layout/AppNavigation.vue')['default']
    CardFood: typeof import('./components/menu/CardFood.vue')['default']
    copy: typeof import('./components/menu/FoodMenusList copy.vue')['default']
    DrinkMenusList: typeof import('./components/menu/DrinkMenusList.vue')['default']
    FoodCard: typeof import('./components/menu/FoodCard.vue')['default']
    FoodMenusList: typeof import('./components/menu/FoodMenusList.vue')['default']
    ImportCSVBtn: typeof import('./components/common/ImportCSVBtn.vue')['default']
    MenuCategory: typeof import('./components/menu/MenuCategory.vue')['default']
    MenuWindow: typeof import('./components/menu/MenuWindow.vue')['default']
    OrderConfirm: typeof import('./components/order/OrderConfirm.vue')['default']
    OrderHistory: typeof import('./components/order/OrderHistory.vue')['default']
    PlaybackAudio: typeof import('./components/PlaybackAudio.vue')['default']
    RecordingButton: typeof import('./components/order/RecordingButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
