version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: app-stage
    container_name: fastapi_app
    expose:
      - "8000"
    networks:
      - appnet

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: nginx-stage
    container_name: nginx_web
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - appnet

networks:
  appnet:
