FROM python:3.13-slim
WORKDIR /app

RUN pip install uv
COPY pyproject.toml .
RUN uv pip install --system .
CMD ["python", "-m", "debugpy", "--listen", "0.0.0.0:5678", "--wait-for-client", "-m", "uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
