services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile-dev
    container_name: fastapi_taskapp_dev
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - devnet

  frontend:
    image: nginx:latest
    container_name: nginx_taskweb_dev
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend:/usr/share/nginx/html
      - ./app/logs:/var/log/nginx
    depends_on:
      - backend
    networks:
      - devnet   # ✅ backendと同じネットワークに！

networks:
  devnet:
