version: '3.8'

services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./data:/app/src/data
    environment:
      - NODE_ENV=development
    command: npx ts-node src/gui/server.ts
