# ベースイメージ
FROM node:18

# 作業ディレクトリを作成
WORKDIR /app

# package.jsonとpackage-lock.jsonを先にコピーして依存関係をインストール
COPY package*.json ./
RUN npm install

# ソースコードをコピー
COPY . .

# TypeScriptをビルド
#RUN npx tsc

# ポート公開
EXPOSE 3000

# 本番用コマンド
CMD ["npx", "nodemon", "--watch", "src", "--ext", "ts", "--exec", "ts-node", "src/gui/server.ts"]
# CMD ["node", "dist/gui/server.js"]
