version: '3'
services:
  backend:
    build: ./backend
    container_name: simple_backend
    expose:
      - "8000"
    networks:
      - appnet
  nginx:
    image: nginx:latest
    container_name: simple_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend
    networks:
      - appnet
networks:
  appnet:
