version: '3'
services:
  web:
    image: nginx:alpine
    container_name: nginx_static_site
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
