services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile-dev
    container_name: fastapi_app_dev
    ports:
      - "8000:8000"
      - "5678:5678"
    volumes:
      - ./app:/app
    networks:
      - devnet

  frontend:
    image: nginx:latest
    container_name: nginx_web_dev
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend:/usr/share/nginx/html
      - ./app/logs:/var/log/nginx
    depends_on:
      - backend
    networks:
      - devnet   # ✅ backendと同じネットワークに！

networks:
  devnet:
